### ISSUE TITLE
Words being pulled back aren't all words

### ISSUE THREAD

**Issue by pseudopants** [rayani1203/Wordle-Game#1]
I'm not really a coder, so was looking for something I could play around with to learn a bit, so first off, thank you!

In messing around, I started running into words that weren't words, so I set the guess count for getting it incorrect to 1, and started testing. Some of the words it was using:

GET IN
DEFAT
CUT UP

I might try moving some of your code that tests that the user entered a real word, up to the API call section. In any case, wanted to give you a heads up.

**Comment by rayani1203** [comment]
Thank you! Yes, I noticed the same when I pulled a random 5 letter word a lot of the words were unheard of or hyphenated or something else that caused an issue. I've since changed it to only pull verbs and that seems to resolve a majority of the issues with that though,

**Comment by pseudopants** [comment]
I think the code I was playing with was after you set it to only pull verbs, so yeah, issues were uncommon, but not completely gone.
